Movie Review and Genre Migrations
codinglabsau/bootcamp pull request #1
Opened 2021-08-20 06:13 UTC by FinnMaladay

Created basic datatables for movie review and genre migrations

Added softDelete for review and movie

2021-08-26 02:43 UTC, vrodriguero requested changes
Hey @FinnMaladay awesome work!!!! 👏 👏 

I left some comments and suggestions in relation to best practices and conventions! But the needy and greedy was spot on! 🥳

2021-08-26 02:43 UTC, vrodriguero commented on app/Models/Movie.php
> +         * */
Great work with the relations @FinnMaladay ! 😄 

In this section, the standard is actually to keep comments to a minimum, which is very different from what I learned at uni hehe. But, that is mainly because Laravel methods are pretty much self-explanatory.

However, if you really want to add comments I would suggest adding them before the method like this:
```
     /**
     * Calls relation of Movie to Genre through genre_movies,
     */
    public function genres() : Relations\BelongsToMany
    {
        //
    }
```

Also as you notice, I added the `: Relations/BelongsToMany`, which specifies what the method will return. And you will need to import the `use Illuminate\Database\Eloquent\Relations`; at the top of the class.

2021-08-26 02:43 UTC, vrodriguero commented on app/Models/Movie.php
> +use Illuminate\Database\Eloquent\SoftDeletes;
Here at CodingLabs we have some code formatting guidelines, which I will present to you guys during the reviews 😄 . By the end, you guys will be pretty used to it ;D 

In relation to the imports we usually format them according to the length and alphabetical order:

```
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
```
if the import is the same length, then we order them in alphabetical order. 

```
use App\Models\Post;
use App\Models\User;
use App\Models\Comment;
```

2021-08-26 02:43 UTC, vrodriguero commented on app/Models/Review.php
> +use Illuminate\Database\Eloquent\SoftDeletes;
Same as the comment above ;D

2021-08-26 02:43 UTC, vrodriguero commented on database/factories/GenreFactory.php
> +use Illuminate\Database\Eloquent\Factories\Factory;
Great formatting!

2021-08-26 02:43 UTC, vrodriguero commented on database/factories/GenreFactory.php
> +            //
you can remove the //

2021-08-26 02:43 UTC, vrodriguero commented on database/factories/Genre_MovieFactory.php
> +class Genre_MovieFactory extends Factory
So based on Laravel's naming convention with pivot tables, we do not need the `_` in the name 😄 
You can rename this to GenreMovieFactory. 
So the model will also be GenreMovie, and the table will be genre_movie

2021-08-26 02:43 UTC, vrodriguero commented on database/factories/MovieFactory.php
> +            //
you can remove this `//`

The factory definition is correct!! Great work ;D 
For formatting, just make sure you have a space before and after the `=>`

2021-08-26 02:43 UTC, vrodriguero commented on database/factories/ReviewFactory.php
> +            //
Same comment as above ;D

2021-08-26 02:43 UTC, vrodriguero commented on database/migrations/2021_08_20_051510_create_reviews_table.php
> +            $table->softDeletes();
because we are using `softDeletes()` it is usually common to have that column to be the last one in the table. So my suggestion would be to move to the last item in this array :D

2021-08-26 02:43 UTC, vrodriguero commented on database/migrations/2021_08_20_051643_create_genres_table.php
> +            $table->timestamps();
Can a genre be deleted? If yes, we can also add the softDeletes here and enable on the model too 😃

2021-08-26 02:43 UTC, vrodriguero commented on database/migrations/2021_08_20_065721_create_movies_table.php
> +            $table->text('blurb')->nullable;
To make a column nullable, I believe you need the `()` at the end of nullable ;D 

You can test this on your TablePlus->structure :D

2021-08-26 02:43 UTC, vrodriguero commented on database/migrations/2021_08_20_065721_create_movies_table.php
> +            $table->softDeletes();
Nice!!!! 🥳

2021-08-26 02:43 UTC, vrodriguero commented on database/migrations/2021_08_25_230804_create_genre__movies_table.php
> +        Schema::create('genre__movies', function (Blueprint $table) {
So this should be named CreateGenreMovieTable , and in the schema you will be creating the genre_movie instead of `genre_movies` 😉

2021-08-26 02:43 UTC, vrodriguero commented on database/migrations/2021_08_25_230804_create_genre__movies_table.php
> +            $table->integer('genre_id');
I believe that for foreign keys it is best to make them of type of `unsignedInteger` instead of integer ;D

2021-08-26 05:46 UTC, FinnMaladay commented
Changes have been made to branch as asked by pull request review

2021-08-26 06:07 UTC, vrodriguero requested changes
@FinnMaladay Amazing!!! 

The code looks very clean and it is great to see such great progress with your Laravel learning!

Very little small changes that I might have missed on the first pass 😅

2021-08-26 06:07 UTC, vrodriguero commented on app/Models/Genre.php
> +use Illuminate\Database\Eloquent\Relations;
Only the order 😄

2021-08-26 06:07 UTC, vrodriguero commented on app/Models/Genre.php
> +    public function movie() : Relations\BelongsToMany
Also, I am sorry I might have missed this. But because a genre can have more than one movie related to it, we would normally name this function `movies()`. 

On the contrary, a review that can only be attached to one user the function would be `user()` 😄

2021-08-26 06:07 UTC, vrodriguero commented on app/Models/GenreMovie.php
> +use Illuminate\Database\Eloquent\Model;
Only the order :D

2021-08-26 06:07 UTC, vrodriguero commented on app/Models/Movie.php
> +use Illuminate\Database\Eloquent\Relations\Relation;
same here 😉

2021-08-26 06:07 UTC, vrodriguero commented on app/Models/Movie.php
> +    use HasFactory;
you can simplify this by doing `use SoftDeletes, HasFactory;`

2021-08-26 06:07 UTC, vrodriguero commented on app/Models/Movie.php
> +    public function genres() : Relations\BelongsToMany
Awesome! 🥳

2021-08-26 06:07 UTC, vrodriguero commented on database/factories/GenreMovieFactory.php
> +            //
you can remove the //

2021-08-26 06:07 UTC, vrodriguero commented on database/factories/MovieFactory.php
> +
you can remove this extra line ;D

2021-09-02 01:33 UTC, vrodriguero approved these changes

2021-09-02 01:33 UTC, merged